name: pre-commit autoupdate

on:
  schedule:
    - cron: 0 4 * * 1
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  precommit-autoupdate:
    name: pre-commit autoupdate
    permissions:
      contents: write # (read) actions/checkout, (write) git push
      pull-requests: write # gh pr create
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.x

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate

      - name: Create Pull Request
        run: |
          branch_name="precommit-autoupdate"
          commit_msg="chore(pre-commit): autoupdate"
          body="Automated weekly update of pre-commit hooks."
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git switch --create "$branch_name"
          git add .
          git commit -m "$commit_msg" || exit 0
          git remote set-url origin "https://x-access-token:$GH_TOKEN@github.com/$repository"
          git push -u origin "$branch_name" --force

          gh pr create --title "$commit_msg" --body "$body"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
