name: pre-commit autoupdate

on:
  schedule:
    - cron: 0 4 * * 1
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  precommit-autoupdate:
    name: pre-commit autoupdate
    permissions:
      contents: write # (read) actions/checkout, (write) peter-evans/create-pull-request
      pull-requests: write # peter-evans/create-pull-request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.x

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate

      - name: Create Pull Request
        run: |
          branch_name="precommit-autoupdate"
          commit_msg="chore(pre-commit): autoupdate"
          body="Automated weekly update of pre-commit hooks."
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git switch --create "$branch_name"
          git add .
          git commit -m "$commit_msg" || exit 0
          git remote set-url origin "https://x-access-token:$GH_TOKEN@github.com/$repository"
          git push -u origin "$branch_name" --force

          gh pr create --title "$commit_msg" --body "$body"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
